// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv/order/proto/order.proto

package order

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderObject_PayStatus int32

const (
	OrderObject_BE_PAID       OrderObject_PayStatus = 0
	OrderObject_PAID          OrderObject_PayStatus = 1
	OrderObject_PAY_EXCEPTION OrderObject_PayStatus = 2
)

var OrderObject_PayStatus_name = map[int32]string{
	0: "BE_PAID",
	1: "PAID",
	2: "PAY_EXCEPTION",
}

var OrderObject_PayStatus_value = map[string]int32{
	"BE_PAID":       0,
	"PAID":          1,
	"PAY_EXCEPTION": 2,
}

func (x OrderObject_PayStatus) String() string {
	return proto.EnumName(OrderObject_PayStatus_name, int32(x))
}

func (OrderObject_PayStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dc4dee17e320b1ee, []int{3, 0}
}

type GetRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc4dee17e320b1ee, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type SearchRequest struct {
	PageNo               uint32               `protobuf:"varint,1,opt,name=pageNo,proto3" json:"pageNo,omitempty"`
	PageSize             uint32               `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	BeginDateTime        *timestamp.Timestamp `protobuf:"bytes,3,opt,name=beginDateTime,proto3" json:"beginDateTime,omitempty"`
	EndDateTime          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=endDateTime,proto3" json:"endDateTime,omitempty"`
	OrderId              string               `protobuf:"bytes,5,opt,name=orderId,proto3" json:"orderId,omitempty"`
	PhoneNumber          string               `protobuf:"bytes,6,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	IsShipped            bool                 `protobuf:"varint,7,opt,name=isShipped,proto3" json:"isShipped,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc4dee17e320b1ee, []int{1}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetPageNo() uint32 {
	if m != nil {
		return m.PageNo
	}
	return 0
}

func (m *SearchRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *SearchRequest) GetBeginDateTime() *timestamp.Timestamp {
	if m != nil {
		return m.BeginDateTime
	}
	return nil
}

func (m *SearchRequest) GetEndDateTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndDateTime
	}
	return nil
}

func (m *SearchRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *SearchRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *SearchRequest) GetIsShipped() bool {
	if m != nil {
		return m.IsShipped
	}
	return false
}

type SearchResult struct {
	PageNo               uint32         `protobuf:"varint,1,opt,name=pageNo,proto3" json:"pageNo,omitempty"`
	PageTotal            uint32         `protobuf:"varint,2,opt,name=pageTotal,proto3" json:"pageTotal,omitempty"`
	Datas                []*OrderObject `protobuf:"bytes,3,rep,name=datas,proto3" json:"datas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SearchResult) Reset()         { *m = SearchResult{} }
func (m *SearchResult) String() string { return proto.CompactTextString(m) }
func (*SearchResult) ProtoMessage()    {}
func (*SearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc4dee17e320b1ee, []int{2}
}

func (m *SearchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResult.Unmarshal(m, b)
}
func (m *SearchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResult.Marshal(b, m, deterministic)
}
func (m *SearchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResult.Merge(m, src)
}
func (m *SearchResult) XXX_Size() int {
	return xxx_messageInfo_SearchResult.Size(m)
}
func (m *SearchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResult.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResult proto.InternalMessageInfo

func (m *SearchResult) GetPageNo() uint32 {
	if m != nil {
		return m.PageNo
	}
	return 0
}

func (m *SearchResult) GetPageTotal() uint32 {
	if m != nil {
		return m.PageTotal
	}
	return 0
}

func (m *SearchResult) GetDatas() []*OrderObject {
	if m != nil {
		return m.Datas
	}
	return nil
}

type OrderObject struct {
	OrderId              string                `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	CreateAt             *timestamp.Timestamp  `protobuf:"bytes,2,opt,name=createAt,proto3" json:"createAt,omitempty"`
	ProductName          string                `protobuf:"bytes,3,opt,name=productName,proto3" json:"productName,omitempty"`
	ProductAmount        float32               `protobuf:"fixed32,4,opt,name=productAmount,proto3" json:"productAmount,omitempty"`
	Name                 string                `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber          string                `protobuf:"bytes,6,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Province             string                `protobuf:"bytes,7,opt,name=province,proto3" json:"province,omitempty"`
	City                 string                `protobuf:"bytes,8,opt,name=city,proto3" json:"city,omitempty"`
	District             string                `protobuf:"bytes,9,opt,name=district,proto3" json:"district,omitempty"`
	Address              string                `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	PayStatus            OrderObject_PayStatus `protobuf:"varint,11,opt,name=payStatus,proto3,enum=order.OrderObject_PayStatus" json:"payStatus,omitempty"`
	PayInfo              *OrderPayInfo         `protobuf:"bytes,12,opt,name=payInfo,proto3" json:"payInfo,omitempty"`
	DeliveryInfo         *OrderDeliveryInfo    `protobuf:"bytes,13,opt,name=deliveryInfo,proto3" json:"deliveryInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *OrderObject) Reset()         { *m = OrderObject{} }
func (m *OrderObject) String() string { return proto.CompactTextString(m) }
func (*OrderObject) ProtoMessage()    {}
func (*OrderObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc4dee17e320b1ee, []int{3}
}

func (m *OrderObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderObject.Unmarshal(m, b)
}
func (m *OrderObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderObject.Marshal(b, m, deterministic)
}
func (m *OrderObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderObject.Merge(m, src)
}
func (m *OrderObject) XXX_Size() int {
	return xxx_messageInfo_OrderObject.Size(m)
}
func (m *OrderObject) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderObject.DiscardUnknown(m)
}

var xxx_messageInfo_OrderObject proto.InternalMessageInfo

func (m *OrderObject) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *OrderObject) GetCreateAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreateAt
	}
	return nil
}

func (m *OrderObject) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *OrderObject) GetProductAmount() float32 {
	if m != nil {
		return m.ProductAmount
	}
	return 0
}

func (m *OrderObject) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OrderObject) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *OrderObject) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *OrderObject) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *OrderObject) GetDistrict() string {
	if m != nil {
		return m.District
	}
	return ""
}

func (m *OrderObject) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *OrderObject) GetPayStatus() OrderObject_PayStatus {
	if m != nil {
		return m.PayStatus
	}
	return OrderObject_BE_PAID
}

func (m *OrderObject) GetPayInfo() *OrderPayInfo {
	if m != nil {
		return m.PayInfo
	}
	return nil
}

func (m *OrderObject) GetDeliveryInfo() *OrderDeliveryInfo {
	if m != nil {
		return m.DeliveryInfo
	}
	return nil
}

type OrderPayInfo struct {
	ModeName             string               `protobuf:"bytes,1,opt,name=modeName,proto3" json:"modeName,omitempty"`
	Money                float32              `protobuf:"fixed32,2,opt,name=money,proto3" json:"money,omitempty"`
	CreateAt             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=createAt,proto3" json:"createAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OrderPayInfo) Reset()         { *m = OrderPayInfo{} }
func (m *OrderPayInfo) String() string { return proto.CompactTextString(m) }
func (*OrderPayInfo) ProtoMessage()    {}
func (*OrderPayInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc4dee17e320b1ee, []int{4}
}

func (m *OrderPayInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderPayInfo.Unmarshal(m, b)
}
func (m *OrderPayInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderPayInfo.Marshal(b, m, deterministic)
}
func (m *OrderPayInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderPayInfo.Merge(m, src)
}
func (m *OrderPayInfo) XXX_Size() int {
	return xxx_messageInfo_OrderPayInfo.Size(m)
}
func (m *OrderPayInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderPayInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OrderPayInfo proto.InternalMessageInfo

func (m *OrderPayInfo) GetModeName() string {
	if m != nil {
		return m.ModeName
	}
	return ""
}

func (m *OrderPayInfo) GetMoney() float32 {
	if m != nil {
		return m.Money
	}
	return 0
}

func (m *OrderPayInfo) GetCreateAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreateAt
	}
	return nil
}

type OrderDeliveryInfo struct {
	CourierCompany       string               `protobuf:"bytes,1,opt,name=courierCompany,proto3" json:"courierCompany,omitempty"`
	WaybillNumber        string               `protobuf:"bytes,2,opt,name=waybillNumber,proto3" json:"waybillNumber,omitempty"`
	CreateAt             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=createAt,proto3" json:"createAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OrderDeliveryInfo) Reset()         { *m = OrderDeliveryInfo{} }
func (m *OrderDeliveryInfo) String() string { return proto.CompactTextString(m) }
func (*OrderDeliveryInfo) ProtoMessage()    {}
func (*OrderDeliveryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc4dee17e320b1ee, []int{5}
}

func (m *OrderDeliveryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDeliveryInfo.Unmarshal(m, b)
}
func (m *OrderDeliveryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDeliveryInfo.Marshal(b, m, deterministic)
}
func (m *OrderDeliveryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDeliveryInfo.Merge(m, src)
}
func (m *OrderDeliveryInfo) XXX_Size() int {
	return xxx_messageInfo_OrderDeliveryInfo.Size(m)
}
func (m *OrderDeliveryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDeliveryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDeliveryInfo proto.InternalMessageInfo

func (m *OrderDeliveryInfo) GetCourierCompany() string {
	if m != nil {
		return m.CourierCompany
	}
	return ""
}

func (m *OrderDeliveryInfo) GetWaybillNumber() string {
	if m != nil {
		return m.WaybillNumber
	}
	return ""
}

func (m *OrderDeliveryInfo) GetCreateAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreateAt
	}
	return nil
}

type CreateRequest struct {
	ProductName          string   `protobuf:"bytes,1,opt,name=productName,proto3" json:"productName,omitempty"`
	ProductAmount        float32  `protobuf:"fixed32,2,opt,name=productAmount,proto3" json:"productAmount,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,4,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	SmsCode              string   `protobuf:"bytes,5,opt,name=smsCode,proto3" json:"smsCode,omitempty"`
	Province             string   `protobuf:"bytes,6,opt,name=province,proto3" json:"province,omitempty"`
	City                 string   `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	Address              string   `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	Time                 uint64   `protobuf:"varint,9,opt,name=time,proto3" json:"time,omitempty"`
	Sign                 string   `protobuf:"bytes,10,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc4dee17e320b1ee, []int{6}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *CreateRequest) GetProductAmount() float32 {
	if m != nil {
		return m.ProductAmount
	}
	return 0
}

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *CreateRequest) GetSmsCode() string {
	if m != nil {
		return m.SmsCode
	}
	return ""
}

func (m *CreateRequest) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *CreateRequest) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *CreateRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CreateRequest) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *CreateRequest) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

type CreateResult struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResult) Reset()         { *m = CreateResult{} }
func (m *CreateResult) String() string { return proto.CompactTextString(m) }
func (*CreateResult) ProtoMessage()    {}
func (*CreateResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc4dee17e320b1ee, []int{7}
}

func (m *CreateResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResult.Unmarshal(m, b)
}
func (m *CreateResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResult.Marshal(b, m, deterministic)
}
func (m *CreateResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResult.Merge(m, src)
}
func (m *CreateResult) XXX_Size() int {
	return xxx_messageInfo_CreateResult.Size(m)
}
func (m *CreateResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResult.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResult proto.InternalMessageInfo

func (m *CreateResult) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type SetDeliveryInfoRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	CourierCompany       string   `protobuf:"bytes,2,opt,name=courierCompany,proto3" json:"courierCompany,omitempty"`
	WaybillNumber        string   `protobuf:"bytes,3,opt,name=waybillNumber,proto3" json:"waybillNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDeliveryInfoRequest) Reset()         { *m = SetDeliveryInfoRequest{} }
func (m *SetDeliveryInfoRequest) String() string { return proto.CompactTextString(m) }
func (*SetDeliveryInfoRequest) ProtoMessage()    {}
func (*SetDeliveryInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc4dee17e320b1ee, []int{8}
}

func (m *SetDeliveryInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDeliveryInfoRequest.Unmarshal(m, b)
}
func (m *SetDeliveryInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDeliveryInfoRequest.Marshal(b, m, deterministic)
}
func (m *SetDeliveryInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDeliveryInfoRequest.Merge(m, src)
}
func (m *SetDeliveryInfoRequest) XXX_Size() int {
	return xxx_messageInfo_SetDeliveryInfoRequest.Size(m)
}
func (m *SetDeliveryInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDeliveryInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetDeliveryInfoRequest proto.InternalMessageInfo

func (m *SetDeliveryInfoRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *SetDeliveryInfoRequest) GetCourierCompany() string {
	if m != nil {
		return m.CourierCompany
	}
	return ""
}

func (m *SetDeliveryInfoRequest) GetWaybillNumber() string {
	if m != nil {
		return m.WaybillNumber
	}
	return ""
}

type SetPayInfoRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	ModeName             string   `protobuf:"bytes,2,opt,name=modeName,proto3" json:"modeName,omitempty"`
	Money                float32  `protobuf:"fixed32,3,opt,name=money,proto3" json:"money,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPayInfoRequest) Reset()         { *m = SetPayInfoRequest{} }
func (m *SetPayInfoRequest) String() string { return proto.CompactTextString(m) }
func (*SetPayInfoRequest) ProtoMessage()    {}
func (*SetPayInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc4dee17e320b1ee, []int{9}
}

func (m *SetPayInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPayInfoRequest.Unmarshal(m, b)
}
func (m *SetPayInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPayInfoRequest.Marshal(b, m, deterministic)
}
func (m *SetPayInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPayInfoRequest.Merge(m, src)
}
func (m *SetPayInfoRequest) XXX_Size() int {
	return xxx_messageInfo_SetPayInfoRequest.Size(m)
}
func (m *SetPayInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPayInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetPayInfoRequest proto.InternalMessageInfo

func (m *SetPayInfoRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *SetPayInfoRequest) GetModeName() string {
	if m != nil {
		return m.ModeName
	}
	return ""
}

func (m *SetPayInfoRequest) GetMoney() float32 {
	if m != nil {
		return m.Money
	}
	return 0
}

func init() {
	proto.RegisterEnum("order.OrderObject_PayStatus", OrderObject_PayStatus_name, OrderObject_PayStatus_value)
	proto.RegisterType((*GetRequest)(nil), "order.GetRequest")
	proto.RegisterType((*SearchRequest)(nil), "order.SearchRequest")
	proto.RegisterType((*SearchResult)(nil), "order.SearchResult")
	proto.RegisterType((*OrderObject)(nil), "order.OrderObject")
	proto.RegisterType((*OrderPayInfo)(nil), "order.OrderPayInfo")
	proto.RegisterType((*OrderDeliveryInfo)(nil), "order.OrderDeliveryInfo")
	proto.RegisterType((*CreateRequest)(nil), "order.CreateRequest")
	proto.RegisterType((*CreateResult)(nil), "order.CreateResult")
	proto.RegisterType((*SetDeliveryInfoRequest)(nil), "order.SetDeliveryInfoRequest")
	proto.RegisterType((*SetPayInfoRequest)(nil), "order.SetPayInfoRequest")
}

func init() {
	proto.RegisterFile("srv/order/proto/order.proto", fileDescriptor_dc4dee17e320b1ee)
}

var fileDescriptor_dc4dee17e320b1ee = []byte{
	// 825 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x4d, 0x6f, 0xda, 0x4c,
	0x10, 0xc6, 0x36, 0x9f, 0x03, 0xe4, 0x0d, 0x9b, 0x28, 0xb2, 0x48, 0x5e, 0xbd, 0xc8, 0x7a, 0x15,
	0x71, 0x29, 0x91, 0xa8, 0xd2, 0x43, 0x95, 0x43, 0x28, 0x41, 0x11, 0x3d, 0x10, 0x64, 0x38, 0xb4,
	0xa7, 0xc8, 0xd8, 0x1b, 0xe2, 0x0a, 0x7b, 0x5d, 0x7b, 0x9d, 0x96, 0x9e, 0xfa, 0x37, 0x7a, 0xe8,
	0xa9, 0x3f, 0xa1, 0x7f, 0xb0, 0xda, 0x5d, 0xdb, 0xd8, 0x7c, 0x24, 0xa8, 0x17, 0x34, 0x33, 0xfb,
	0xcc, 0x7a, 0xf6, 0x99, 0x67, 0x76, 0x81, 0xd3, 0xc0, 0x7f, 0xba, 0x20, 0xbe, 0x85, 0xfd, 0x0b,
	0xcf, 0x27, 0x94, 0x08, 0xbb, 0xc3, 0x6d, 0x54, 0xe0, 0x4e, 0xf3, 0x74, 0x4e, 0xc8, 0x7c, 0x81,
	0x05, 0x60, 0x16, 0x3e, 0x5c, 0x60, 0xc7, 0xa3, 0x4b, 0x81, 0x69, 0xfe, 0xb7, 0xbe, 0x48, 0x6d,
	0x07, 0x07, 0xd4, 0x70, 0x3c, 0x01, 0xd0, 0xce, 0x01, 0x6e, 0x31, 0xd5, 0xf1, 0xe7, 0x10, 0x07,
	0x14, 0xa9, 0x50, 0xe2, 0x9b, 0x0e, 0x2d, 0x55, 0x6a, 0x49, 0xed, 0x8a, 0x1e, 0xbb, 0xda, 0x4f,
	0x19, 0xea, 0x13, 0x6c, 0xf8, 0xe6, 0x63, 0x8c, 0x3d, 0x81, 0xa2, 0x67, 0xcc, 0xf1, 0x88, 0x70,
	0x68, 0x5d, 0x8f, 0x3c, 0xd4, 0x84, 0x32, 0xb3, 0x26, 0xf6, 0x37, 0xac, 0xca, 0x7c, 0x25, 0xf1,
	0xd1, 0x35, 0xd4, 0x67, 0x78, 0x6e, 0xbb, 0x37, 0x06, 0xc5, 0x53, 0xdb, 0xc1, 0xaa, 0xd2, 0x92,
	0xda, 0xd5, 0x6e, 0xb3, 0x23, 0xca, 0xec, 0xc4, 0x65, 0x76, 0xa6, 0x71, 0x99, 0x7a, 0x36, 0x01,
	0x5d, 0x41, 0x15, 0xbb, 0x56, 0x92, 0x9f, 0x7f, 0x31, 0x3f, 0x0d, 0x4f, 0x9f, 0xaf, 0x90, 0x39,
	0x1f, 0x6a, 0x41, 0xd5, 0x7b, 0x24, 0x2e, 0x1e, 0x85, 0xce, 0x0c, 0xfb, 0x6a, 0x91, 0xaf, 0xa6,
	0x43, 0xe8, 0x0c, 0x2a, 0x76, 0x30, 0x79, 0xb4, 0x3d, 0x0f, 0x5b, 0x6a, 0xa9, 0x25, 0xb5, 0xcb,
	0xfa, 0x2a, 0xa0, 0xb9, 0x50, 0x8b, 0xe9, 0x09, 0xc2, 0xc5, 0x6e, 0x76, 0xce, 0xa0, 0xc2, 0xac,
	0x29, 0xa1, 0xc6, 0x22, 0xa2, 0x67, 0x15, 0x40, 0x6d, 0x28, 0x58, 0x06, 0x35, 0x02, 0x55, 0x69,
	0x29, 0xed, 0x6a, 0x17, 0x75, 0x44, 0xbf, 0xef, 0xd8, 0xef, 0xdd, 0xec, 0x13, 0x36, 0xa9, 0x2e,
	0x00, 0xda, 0xaf, 0x3c, 0x54, 0x53, 0xe1, 0xdd, 0x9d, 0x43, 0x6f, 0xa0, 0x6c, 0xfa, 0xd8, 0xa0,
	0xb8, 0x47, 0xf9, 0x07, 0x9f, 0xa7, 0x2b, 0xc1, 0x72, 0x46, 0x7c, 0x62, 0x85, 0x26, 0x1d, 0x19,
	0x51, 0xa7, 0x18, 0x23, 0xab, 0x10, 0xfa, 0x1f, 0xea, 0x91, 0xdb, 0x73, 0x48, 0xe8, 0x52, 0xde,
	0x0d, 0x59, 0xcf, 0x06, 0x11, 0x82, 0xbc, 0xcb, 0x36, 0x10, 0x84, 0x73, 0x7b, 0x0f, 0xb6, 0x99,
	0x8a, 0x7c, 0xf2, 0x64, 0xbb, 0x26, 0xe6, 0x64, 0x57, 0xf4, 0xc4, 0x67, 0x3b, 0x9a, 0x36, 0x5d,
	0xaa, 0x65, 0xb1, 0x23, 0xb3, 0x19, 0xde, 0xb2, 0x03, 0xea, 0xdb, 0x26, 0x55, 0x2b, 0x02, 0x1f,
	0xfb, 0x8c, 0x1b, 0xc3, 0xb2, 0x7c, 0x1c, 0x04, 0x2a, 0x08, 0x6e, 0x22, 0x17, 0xbd, 0x65, 0xdd,
	0x58, 0x4e, 0xa8, 0x41, 0xc3, 0x40, 0xad, 0xb6, 0xa4, 0xf6, 0x41, 0xf7, 0x6c, 0x93, 0xf3, 0xce,
	0x38, 0xc6, 0xe8, 0x2b, 0x38, 0x7a, 0x05, 0x25, 0xcf, 0x58, 0x0e, 0xdd, 0x07, 0xa2, 0xd6, 0x38,
	0xad, 0x47, 0xe9, 0xcc, 0xb1, 0x58, 0xd2, 0x63, 0x0c, 0xba, 0x82, 0x9a, 0x85, 0x17, 0xf6, 0x13,
	0xf6, 0x45, 0x4e, 0x9d, 0xe7, 0xa8, 0xe9, 0x9c, 0x9b, 0xd4, 0xba, 0x9e, 0x41, 0x6b, 0x97, 0x50,
	0x49, 0x8a, 0x40, 0x55, 0x28, 0xbd, 0x1b, 0xdc, 0x8f, 0x7b, 0xc3, 0x9b, 0xc3, 0x1c, 0x2a, 0x43,
	0x9e, 0x5b, 0x12, 0x6a, 0x40, 0x7d, 0xdc, 0xfb, 0x78, 0x3f, 0xf8, 0xd0, 0x1f, 0x8c, 0xa7, 0xc3,
	0xbb, 0xd1, 0xa1, 0xac, 0x7d, 0x85, 0x5a, 0xba, 0x1a, 0xc6, 0x92, 0x43, 0x2c, 0xcc, 0x1b, 0x2a,
	0x64, 0x92, 0xf8, 0xe8, 0x18, 0x0a, 0x0e, 0x71, 0xf1, 0x92, 0x8b, 0x44, 0xd6, 0x85, 0x93, 0x51,
	0x8f, 0xb2, 0xbf, 0x7a, 0xb4, 0x1f, 0x12, 0x34, 0x36, 0x0e, 0x85, 0xce, 0xe1, 0xc0, 0x24, 0xa1,
	0x6f, 0x63, 0xbf, 0x4f, 0x1c, 0xcf, 0x70, 0x97, 0x51, 0x15, 0x6b, 0x51, 0xa6, 0xac, 0x2f, 0xc6,
	0x72, 0x66, 0x2f, 0x16, 0x91, 0x42, 0x64, 0x0e, 0xcb, 0x06, 0xff, 0xbe, 0x36, 0x19, 0xea, 0x7d,
	0xee, 0xc4, 0x77, 0xd9, 0x9a, 0xd6, 0xa5, 0x3d, 0xb4, 0x2e, 0x3f, 0xa7, 0x75, 0x65, 0xb7, 0xd6,
	0xf3, 0x9b, 0x5a, 0x57, 0xa1, 0x14, 0x38, 0x41, 0x9f, 0x58, 0xf1, 0x90, 0xc4, 0x6e, 0x66, 0x0a,
	0x8a, 0x3b, 0xa6, 0xa0, 0x94, 0x9a, 0x82, 0x94, 0xd2, 0xcb, 0x59, 0xa5, 0x23, 0xc8, 0xb3, 0xab,
	0x9f, 0xcf, 0x46, 0x5e, 0xe7, 0x36, 0x8b, 0x05, 0xf6, 0xdc, 0x8d, 0x86, 0x82, 0xdb, 0x5a, 0x1b,
	0x6a, 0x31, 0x35, 0xfc, 0x1e, 0xdb, 0xfd, 0x22, 0x7c, 0x97, 0xe0, 0x64, 0x82, 0x69, 0x46, 0xb4,
	0x2f, 0x3d, 0x23, 0x5b, 0x04, 0x20, 0xef, 0x27, 0x00, 0x65, 0x8b, 0x00, 0xb4, 0x7b, 0x68, 0x4c,
	0x30, 0x8d, 0x47, 0xed, 0xc5, 0x8f, 0xa7, 0xd5, 0x2f, 0xef, 0x52, 0xbf, 0x92, 0x52, 0x7f, 0xf7,
	0xb7, 0x0c, 0x05, 0xae, 0x62, 0xd4, 0x01, 0xe5, 0x16, 0x53, 0xd4, 0x88, 0xe6, 0x75, 0xf5, 0x66,
	0x36, 0xb7, 0x5c, 0xd2, 0x5a, 0x0e, 0x5d, 0x42, 0x51, 0xbc, 0x07, 0xe8, 0x38, 0x5a, 0xcf, 0xbc,
	0x9e, 0xcd, 0xa3, 0xb5, 0x28, 0x23, 0x5b, 0xa4, 0x09, 0xfa, 0x93, 0xb4, 0x8c, 0x50, 0x93, 0xb4,
	0x74, 0x8f, 0xb4, 0x1c, 0x7a, 0x0f, 0xff, 0xac, 0xb5, 0x02, 0xfd, 0x9b, 0x7c, 0x60, 0x5b, 0x8b,
	0x9a, 0x27, 0x1b, 0x93, 0x32, 0x60, 0x7f, 0x1b, 0xb4, 0x1c, 0xba, 0x06, 0x58, 0x91, 0x8a, 0xd4,
	0xd5, 0x36, 0x59, 0x9e, 0x77, 0xef, 0x30, 0x2b, 0xf2, 0xc8, 0xeb, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x80, 0x2f, 0x6c, 0xce, 0xbe, 0x08, 0x00, 0x00,
}
