// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv/smscode/proto/smscode.proto

package smscode

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateVerificationCodeRequest struct {
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateVerificationCodeRequest) Reset()         { *m = CreateVerificationCodeRequest{} }
func (m *CreateVerificationCodeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateVerificationCodeRequest) ProtoMessage()    {}
func (*CreateVerificationCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68d4657a98032ecf, []int{0}
}

func (m *CreateVerificationCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVerificationCodeRequest.Unmarshal(m, b)
}
func (m *CreateVerificationCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVerificationCodeRequest.Marshal(b, m, deterministic)
}
func (m *CreateVerificationCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVerificationCodeRequest.Merge(m, src)
}
func (m *CreateVerificationCodeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateVerificationCodeRequest.Size(m)
}
func (m *CreateVerificationCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVerificationCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVerificationCodeRequest proto.InternalMessageInfo

func (m *CreateVerificationCodeRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type CreateVerificationCodeResult struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateVerificationCodeResult) Reset()         { *m = CreateVerificationCodeResult{} }
func (m *CreateVerificationCodeResult) String() string { return proto.CompactTextString(m) }
func (*CreateVerificationCodeResult) ProtoMessage()    {}
func (*CreateVerificationCodeResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_68d4657a98032ecf, []int{1}
}

func (m *CreateVerificationCodeResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVerificationCodeResult.Unmarshal(m, b)
}
func (m *CreateVerificationCodeResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVerificationCodeResult.Marshal(b, m, deterministic)
}
func (m *CreateVerificationCodeResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVerificationCodeResult.Merge(m, src)
}
func (m *CreateVerificationCodeResult) XXX_Size() int {
	return xxx_messageInfo_CreateVerificationCodeResult.Size(m)
}
func (m *CreateVerificationCodeResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVerificationCodeResult.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVerificationCodeResult proto.InternalMessageInfo

func (m *CreateVerificationCodeResult) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type CheckVerificationCodeRequest struct {
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckVerificationCodeRequest) Reset()         { *m = CheckVerificationCodeRequest{} }
func (m *CheckVerificationCodeRequest) String() string { return proto.CompactTextString(m) }
func (*CheckVerificationCodeRequest) ProtoMessage()    {}
func (*CheckVerificationCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68d4657a98032ecf, []int{2}
}

func (m *CheckVerificationCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckVerificationCodeRequest.Unmarshal(m, b)
}
func (m *CheckVerificationCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckVerificationCodeRequest.Marshal(b, m, deterministic)
}
func (m *CheckVerificationCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckVerificationCodeRequest.Merge(m, src)
}
func (m *CheckVerificationCodeRequest) XXX_Size() int {
	return xxx_messageInfo_CheckVerificationCodeRequest.Size(m)
}
func (m *CheckVerificationCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckVerificationCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckVerificationCodeRequest proto.InternalMessageInfo

func (m *CheckVerificationCodeRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *CheckVerificationCodeRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type CheckVerificationCodeResult struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckVerificationCodeResult) Reset()         { *m = CheckVerificationCodeResult{} }
func (m *CheckVerificationCodeResult) String() string { return proto.CompactTextString(m) }
func (*CheckVerificationCodeResult) ProtoMessage()    {}
func (*CheckVerificationCodeResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_68d4657a98032ecf, []int{3}
}

func (m *CheckVerificationCodeResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckVerificationCodeResult.Unmarshal(m, b)
}
func (m *CheckVerificationCodeResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckVerificationCodeResult.Marshal(b, m, deterministic)
}
func (m *CheckVerificationCodeResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckVerificationCodeResult.Merge(m, src)
}
func (m *CheckVerificationCodeResult) XXX_Size() int {
	return xxx_messageInfo_CheckVerificationCodeResult.Size(m)
}
func (m *CheckVerificationCodeResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckVerificationCodeResult.DiscardUnknown(m)
}

var xxx_messageInfo_CheckVerificationCodeResult proto.InternalMessageInfo

func (m *CheckVerificationCodeResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type SmscodeModel struct {
	PhoneNumber          string               `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty" bson:"phoneNumber"`
	Code                 string               `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty" bson:"code"`
	CreateAt             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=createAt,proto3" json:"createAt,omitempty" bson:"createAt"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *SmscodeModel) Reset()         { *m = SmscodeModel{} }
func (m *SmscodeModel) String() string { return proto.CompactTextString(m) }
func (*SmscodeModel) ProtoMessage()    {}
func (*SmscodeModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_68d4657a98032ecf, []int{4}
}

func (m *SmscodeModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmscodeModel.Unmarshal(m, b)
}
func (m *SmscodeModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmscodeModel.Marshal(b, m, deterministic)
}
func (m *SmscodeModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmscodeModel.Merge(m, src)
}
func (m *SmscodeModel) XXX_Size() int {
	return xxx_messageInfo_SmscodeModel.Size(m)
}
func (m *SmscodeModel) XXX_DiscardUnknown() {
	xxx_messageInfo_SmscodeModel.DiscardUnknown(m)
}

var xxx_messageInfo_SmscodeModel proto.InternalMessageInfo

func (m *SmscodeModel) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *SmscodeModel) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *SmscodeModel) GetCreateAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreateAt
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateVerificationCodeRequest)(nil), "smscode.CreateVerificationCodeRequest")
	proto.RegisterType((*CreateVerificationCodeResult)(nil), "smscode.CreateVerificationCodeResult")
	proto.RegisterType((*CheckVerificationCodeRequest)(nil), "smscode.CheckVerificationCodeRequest")
	proto.RegisterType((*CheckVerificationCodeResult)(nil), "smscode.CheckVerificationCodeResult")
	proto.RegisterType((*SmscodeModel)(nil), "smscode.SmscodeModel")
}

func init() {
	proto.RegisterFile("srv/smscode/proto/smscode.proto", fileDescriptor_68d4657a98032ecf)
}

var fileDescriptor_68d4657a98032ecf = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x4d, 0x4f, 0xb3, 0x40,
	0x14, 0x85, 0x5f, 0x5e, 0x8d, 0xd4, 0x5b, 0x57, 0x93, 0x68, 0x08, 0xd6, 0x94, 0x10, 0x35, 0x5d,
	0x41, 0x82, 0x89, 0xae, 0x1b, 0xd6, 0xba, 0xc0, 0xc6, 0x3d, 0x0c, 0x97, 0x76, 0x22, 0x74, 0x70,
	0x3e, 0x5c, 0xf9, 0x53, 0xfd, 0x31, 0xa6, 0x03, 0xd3, 0xb0, 0xe8, 0x47, 0xd2, 0xdd, 0x9c, 0xc9,
	0x99, 0x73, 0xee, 0x3c, 0x17, 0xa6, 0x52, 0x7c, 0xc7, 0xb2, 0x91, 0x94, 0x97, 0x18, 0xb7, 0x82,
	0x2b, 0x6e, 0x55, 0x64, 0x14, 0x71, 0x7b, 0xe9, 0x4f, 0x97, 0x9c, 0x2f, 0xeb, 0xde, 0x54, 0xe8,
	0x2a, 0x56, 0xac, 0x41, 0xa9, 0xf2, 0xa6, 0xed, 0x9c, 0xe1, 0x1c, 0xee, 0x52, 0x81, 0xb9, 0xc2,
	0x0f, 0x14, 0xac, 0x62, 0x34, 0x57, 0x8c, 0xaf, 0x53, 0x5e, 0x62, 0x86, 0x5f, 0x1a, 0xa5, 0x22,
	0x01, 0x8c, 0xdb, 0x15, 0x5f, 0xe3, 0x9b, 0x6e, 0x0a, 0x14, 0x9e, 0x13, 0x38, 0xb3, 0xcb, 0x6c,
	0x78, 0x15, 0x26, 0x30, 0xd9, 0x17, 0x21, 0x75, 0xad, 0x08, 0x81, 0xf3, 0xcd, 0x2c, 0xfd, 0x53,
	0x73, 0x0e, 0x17, 0x30, 0x49, 0x57, 0x48, 0x3f, 0x4f, 0x6e, 0xdd, 0xa6, 0xfe, 0x1f, 0xa4, 0xbe,
	0xc0, 0xed, 0x9e, 0x54, 0x33, 0x88, 0x07, 0xae, 0xd4, 0x94, 0xa2, 0x94, 0x26, 0x70, 0x94, 0x59,
	0x19, 0xfe, 0xc0, 0xd5, 0x7b, 0x47, 0xec, 0x95, 0x97, 0x58, 0x9f, 0x56, 0x4f, 0x9e, 0x61, 0x44,
	0x0d, 0x88, 0xb9, 0xf2, 0xce, 0x02, 0x67, 0x36, 0x4e, 0xfc, 0xa8, 0xe3, 0x1f, 0x59, 0xfe, 0xd1,
	0xc2, 0xf2, 0xcf, 0xb6, 0xde, 0xe4, 0xd7, 0x01, 0xb7, 0xaf, 0x27, 0x0c, 0x6e, 0x76, 0xc3, 0x24,
	0x8f, 0x91, 0xdd, 0xf1, 0xc1, 0x85, 0xf9, 0x0f, 0x47, 0x7d, 0x1b, 0x18, 0xe1, 0x3f, 0x52, 0xc1,
	0xf5, 0x4e, 0x5a, 0x64, 0x90, 0x70, 0x60, 0x47, 0xfe, 0xfd, 0x31, 0x5b, 0xd7, 0x53, 0x5c, 0x98,
	0xcf, 0x3f, 0xfd, 0x05, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x8b, 0xc5, 0x18, 0xb6, 0x02, 0x00, 0x00,
}
