// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv/sms/proto/sms.proto

package sms

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateVerificationCodeRequest struct {
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateVerificationCodeRequest) Reset()         { *m = CreateVerificationCodeRequest{} }
func (m *CreateVerificationCodeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateVerificationCodeRequest) ProtoMessage()    {}
func (*CreateVerificationCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7df243bcfd866b62, []int{0}
}

func (m *CreateVerificationCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVerificationCodeRequest.Unmarshal(m, b)
}
func (m *CreateVerificationCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVerificationCodeRequest.Marshal(b, m, deterministic)
}
func (m *CreateVerificationCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVerificationCodeRequest.Merge(m, src)
}
func (m *CreateVerificationCodeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateVerificationCodeRequest.Size(m)
}
func (m *CreateVerificationCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVerificationCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVerificationCodeRequest proto.InternalMessageInfo

func (m *CreateVerificationCodeRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type CreateVerificationCodeResult struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateVerificationCodeResult) Reset()         { *m = CreateVerificationCodeResult{} }
func (m *CreateVerificationCodeResult) String() string { return proto.CompactTextString(m) }
func (*CreateVerificationCodeResult) ProtoMessage()    {}
func (*CreateVerificationCodeResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_7df243bcfd866b62, []int{1}
}

func (m *CreateVerificationCodeResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVerificationCodeResult.Unmarshal(m, b)
}
func (m *CreateVerificationCodeResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVerificationCodeResult.Marshal(b, m, deterministic)
}
func (m *CreateVerificationCodeResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVerificationCodeResult.Merge(m, src)
}
func (m *CreateVerificationCodeResult) XXX_Size() int {
	return xxx_messageInfo_CreateVerificationCodeResult.Size(m)
}
func (m *CreateVerificationCodeResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVerificationCodeResult.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVerificationCodeResult proto.InternalMessageInfo

func (m *CreateVerificationCodeResult) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type SendVerificationCodeRequest struct {
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendVerificationCodeRequest) Reset()         { *m = SendVerificationCodeRequest{} }
func (m *SendVerificationCodeRequest) String() string { return proto.CompactTextString(m) }
func (*SendVerificationCodeRequest) ProtoMessage()    {}
func (*SendVerificationCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7df243bcfd866b62, []int{2}
}

func (m *SendVerificationCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendVerificationCodeRequest.Unmarshal(m, b)
}
func (m *SendVerificationCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendVerificationCodeRequest.Marshal(b, m, deterministic)
}
func (m *SendVerificationCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendVerificationCodeRequest.Merge(m, src)
}
func (m *SendVerificationCodeRequest) XXX_Size() int {
	return xxx_messageInfo_SendVerificationCodeRequest.Size(m)
}
func (m *SendVerificationCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendVerificationCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendVerificationCodeRequest proto.InternalMessageInfo

func (m *SendVerificationCodeRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *SendVerificationCodeRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type SendOrderConfirmationRequest struct {
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OrderId              string   `protobuf:"bytes,3,opt,name=orderId,proto3" json:"orderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendOrderConfirmationRequest) Reset()         { *m = SendOrderConfirmationRequest{} }
func (m *SendOrderConfirmationRequest) String() string { return proto.CompactTextString(m) }
func (*SendOrderConfirmationRequest) ProtoMessage()    {}
func (*SendOrderConfirmationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7df243bcfd866b62, []int{3}
}

func (m *SendOrderConfirmationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendOrderConfirmationRequest.Unmarshal(m, b)
}
func (m *SendOrderConfirmationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendOrderConfirmationRequest.Marshal(b, m, deterministic)
}
func (m *SendOrderConfirmationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendOrderConfirmationRequest.Merge(m, src)
}
func (m *SendOrderConfirmationRequest) XXX_Size() int {
	return xxx_messageInfo_SendOrderConfirmationRequest.Size(m)
}
func (m *SendOrderConfirmationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendOrderConfirmationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendOrderConfirmationRequest proto.InternalMessageInfo

func (m *SendOrderConfirmationRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *SendOrderConfirmationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SendOrderConfirmationRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type SendShippingNoticeRequest struct {
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	CourierCompany       string   `protobuf:"bytes,2,opt,name=courierCompany,proto3" json:"courierCompany,omitempty"`
	WaybillNumber        string   `protobuf:"bytes,3,opt,name=waybillNumber,proto3" json:"waybillNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendShippingNoticeRequest) Reset()         { *m = SendShippingNoticeRequest{} }
func (m *SendShippingNoticeRequest) String() string { return proto.CompactTextString(m) }
func (*SendShippingNoticeRequest) ProtoMessage()    {}
func (*SendShippingNoticeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7df243bcfd866b62, []int{4}
}

func (m *SendShippingNoticeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendShippingNoticeRequest.Unmarshal(m, b)
}
func (m *SendShippingNoticeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendShippingNoticeRequest.Marshal(b, m, deterministic)
}
func (m *SendShippingNoticeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendShippingNoticeRequest.Merge(m, src)
}
func (m *SendShippingNoticeRequest) XXX_Size() int {
	return xxx_messageInfo_SendShippingNoticeRequest.Size(m)
}
func (m *SendShippingNoticeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendShippingNoticeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendShippingNoticeRequest proto.InternalMessageInfo

func (m *SendShippingNoticeRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *SendShippingNoticeRequest) GetCourierCompany() string {
	if m != nil {
		return m.CourierCompany
	}
	return ""
}

func (m *SendShippingNoticeRequest) GetWaybillNumber() string {
	if m != nil {
		return m.WaybillNumber
	}
	return ""
}

type CheckVerificationCodeRequest struct {
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckVerificationCodeRequest) Reset()         { *m = CheckVerificationCodeRequest{} }
func (m *CheckVerificationCodeRequest) String() string { return proto.CompactTextString(m) }
func (*CheckVerificationCodeRequest) ProtoMessage()    {}
func (*CheckVerificationCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7df243bcfd866b62, []int{5}
}

func (m *CheckVerificationCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckVerificationCodeRequest.Unmarshal(m, b)
}
func (m *CheckVerificationCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckVerificationCodeRequest.Marshal(b, m, deterministic)
}
func (m *CheckVerificationCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckVerificationCodeRequest.Merge(m, src)
}
func (m *CheckVerificationCodeRequest) XXX_Size() int {
	return xxx_messageInfo_CheckVerificationCodeRequest.Size(m)
}
func (m *CheckVerificationCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckVerificationCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckVerificationCodeRequest proto.InternalMessageInfo

func (m *CheckVerificationCodeRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *CheckVerificationCodeRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type CheckVerificationCodeResult struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckVerificationCodeResult) Reset()         { *m = CheckVerificationCodeResult{} }
func (m *CheckVerificationCodeResult) String() string { return proto.CompactTextString(m) }
func (*CheckVerificationCodeResult) ProtoMessage()    {}
func (*CheckVerificationCodeResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_7df243bcfd866b62, []int{6}
}

func (m *CheckVerificationCodeResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckVerificationCodeResult.Unmarshal(m, b)
}
func (m *CheckVerificationCodeResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckVerificationCodeResult.Marshal(b, m, deterministic)
}
func (m *CheckVerificationCodeResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckVerificationCodeResult.Merge(m, src)
}
func (m *CheckVerificationCodeResult) XXX_Size() int {
	return xxx_messageInfo_CheckVerificationCodeResult.Size(m)
}
func (m *CheckVerificationCodeResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckVerificationCodeResult.DiscardUnknown(m)
}

var xxx_messageInfo_CheckVerificationCodeResult proto.InternalMessageInfo

func (m *CheckVerificationCodeResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*CreateVerificationCodeRequest)(nil), "sms.CreateVerificationCodeRequest")
	proto.RegisterType((*CreateVerificationCodeResult)(nil), "sms.CreateVerificationCodeResult")
	proto.RegisterType((*SendVerificationCodeRequest)(nil), "sms.SendVerificationCodeRequest")
	proto.RegisterType((*SendOrderConfirmationRequest)(nil), "sms.SendOrderConfirmationRequest")
	proto.RegisterType((*SendShippingNoticeRequest)(nil), "sms.SendShippingNoticeRequest")
	proto.RegisterType((*CheckVerificationCodeRequest)(nil), "sms.CheckVerificationCodeRequest")
	proto.RegisterType((*CheckVerificationCodeResult)(nil), "sms.CheckVerificationCodeResult")
}

func init() {
	proto.RegisterFile("srv/sms/proto/sms.proto", fileDescriptor_7df243bcfd866b62)
}

var fileDescriptor_7df243bcfd866b62 = []byte{
	// 395 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xcf, 0x4e, 0xdb, 0x40,
	0x10, 0xc6, 0x93, 0xba, 0x6a, 0xda, 0xa9, 0xda, 0xc3, 0xaa, 0x49, 0x5d, 0x27, 0xad, 0xd2, 0x15,
	0x42, 0x9c, 0x1c, 0x29, 0x1c, 0x38, 0x23, 0x8b, 0x03, 0x97, 0x20, 0xd9, 0x11, 0x47, 0x24, 0xff,
	0x99, 0x24, 0x2b, 0xbc, 0xbb, 0x66, 0xd7, 0x06, 0xe5, 0x19, 0x78, 0x2b, 0x9e, 0x0c, 0xad, 0xed,
	0x44, 0x01, 0x1c, 0x4b, 0x41, 0xdc, 0x66, 0xc7, 0x33, 0xbf, 0xf9, 0xbc, 0xfb, 0x0d, 0xfc, 0xd6,
	0xea, 0x7e, 0xa2, 0xb9, 0x9e, 0x64, 0x4a, 0xe6, 0xd2, 0x44, 0x6e, 0x19, 0x11, 0x4b, 0x73, 0xed,
	0x0c, 0x97, 0x52, 0x2e, 0x53, 0xac, 0x3e, 0x46, 0xc5, 0x62, 0x82, 0x3c, 0xcb, 0xd7, 0x55, 0x05,
	0x3d, 0x87, 0xbf, 0x9e, 0xc2, 0x30, 0xc7, 0x6b, 0x54, 0x6c, 0xc1, 0xe2, 0x30, 0x67, 0x52, 0x78,
	0x32, 0x41, 0x1f, 0xef, 0x0a, 0xd4, 0x39, 0x19, 0xc3, 0xf7, 0x6c, 0x25, 0x05, 0xce, 0x0a, 0x1e,
	0xa1, 0xb2, 0xbb, 0xe3, 0xee, 0xc9, 0x37, 0x7f, 0x37, 0x45, 0xa7, 0x30, 0xda, 0x87, 0xd0, 0x45,
	0x9a, 0x13, 0x02, 0x9f, 0x63, 0x99, 0x60, 0xdd, 0x5a, 0xc6, 0x34, 0x80, 0x61, 0x80, 0x22, 0x79,
	0xf7, 0xd0, 0x2d, 0xf4, 0xd3, 0x0e, 0x54, 0xc0, 0xc8, 0x40, 0xaf, 0x54, 0x82, 0xca, 0x93, 0x62,
	0xc1, 0x14, 0x2f, 0xc9, 0x07, 0x51, 0x45, 0xc8, 0xb7, 0x54, 0x13, 0x13, 0x1b, 0x7a, 0xd2, 0x10,
	0x2f, 0x13, 0xdb, 0x2a, 0xd3, 0x9b, 0x23, 0x7d, 0xec, 0xc2, 0x1f, 0x33, 0x30, 0x58, 0xb1, 0x2c,
	0x63, 0x62, 0x39, 0x93, 0x39, 0x8b, 0x0f, 0xf8, 0x87, 0x63, 0xf8, 0x19, 0xcb, 0x42, 0x31, 0xa3,
	0x96, 0x67, 0xa1, 0x58, 0xd7, 0x73, 0x5f, 0x65, 0xc9, 0x11, 0xfc, 0x78, 0x08, 0xd7, 0x11, 0x4b,
	0xd3, 0x9a, 0x55, 0xe9, 0x78, 0x99, 0xa4, 0x73, 0x18, 0x79, 0x2b, 0x8c, 0x6f, 0x3f, 0xf6, 0x4e,
	0xcf, 0x60, 0xb8, 0x87, 0x5a, 0xbe, 0xad, 0x0d, 0x3d, 0x5d, 0xc4, 0x31, 0x6a, 0x5d, 0x02, 0xbf,
	0xfa, 0x9b, 0xe3, 0xf4, 0xc9, 0x02, 0x2b, 0xe0, 0x9a, 0x84, 0x30, 0x68, 0x76, 0x07, 0xa1, 0xae,
	0x31, 0x6a, 0xab, 0xfb, 0x9c, 0xff, 0xad, 0x35, 0x46, 0x02, 0xed, 0x90, 0x1b, 0xe8, 0x37, 0x6a,
	0x24, 0x75, 0x77, 0xcb, 0xad, 0x38, 0xe3, 0xb6, 0x92, 0x9a, 0xef, 0xc3, 0xaf, 0x26, 0xb3, 0x92,
	0xaa, 0xb7, 0xc5, 0xc7, 0xce, 0xc0, 0xad, 0x76, 0xcf, 0xdd, 0xec, 0x9e, 0x7b, 0x61, 0x76, 0x8f,
	0x76, 0xc8, 0x1c, 0xfa, 0x8d, 0x5e, 0xad, 0x35, 0xb7, 0xf9, 0xb8, 0x85, 0x3a, 0x03, 0xf2, 0xd6,
	0x90, 0xe4, 0xdf, 0x16, 0xd9, 0xe8, 0xd4, 0xfd, 0xbc, 0xe8, 0x4b, 0x99, 0x39, 0x7d, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0x95, 0x91, 0x4e, 0x32, 0x61, 0x04, 0x00, 0x00,
}
