// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/sms/proto/sms.proto

package sms

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Time                 string   `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Sign                 string   `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae23ac89f21f6cad, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Request) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Request) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae23ac89f21f6cad, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Request)(nil), "sms.Request")
	proto.RegisterType((*Response)(nil), "sms.Response")
}

func init() {
	proto.RegisterFile("api/sms/proto/sms.proto", fileDescriptor_ae23ac89f21f6cad)
}

var fileDescriptor_ae23ac89f21f6cad = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0x3f, 0x0f, 0x82, 0x30,
	0x10, 0x47, 0x45, 0x8c, 0x7f, 0x4e, 0x5d, 0x1a, 0x13, 0x89, 0x13, 0x61, 0x72, 0x82, 0x44, 0xe3,
	0xe6, 0xe6, 0xee, 0x00, 0x89, 0x3b, 0xc8, 0xa9, 0x37, 0xb4, 0x57, 0xb9, 0xf2, 0xfd, 0x4d, 0x0b,
	0x83, 0xdb, 0xbb, 0x77, 0xf9, 0x25, 0x0f, 0xf6, 0xb5, 0xa5, 0x42, 0xb4, 0x14, 0xb6, 0x63, 0xc7,
	0x9e, 0xf2, 0x40, 0x2a, 0x16, 0x2d, 0x59, 0x05, 0x8b, 0x12, 0xbf, 0x3d, 0x8a, 0x53, 0x29, 0xac,
	0xed, 0x87, 0x0d, 0xde, 0x7b, 0xdd, 0x60, 0x97, 0x44, 0x69, 0x74, 0x5c, 0x95, 0xff, 0x4a, 0x29,
	0x98, 0x39, 0xd2, 0x98, 0x4c, 0xc3, 0x2b, 0xb0, 0x77, 0x42, 0x6f, 0x93, 0xc4, 0x83, 0xf3, 0x9c,
	0x01, 0x2c, 0x4b, 0x14, 0xcb, 0x46, 0xf0, 0x74, 0x85, 0xb8, 0xd2, 0xa2, 0x2e, 0xb0, 0xab, 0xd0,
	0xb4, 0x0f, 0xec, 0xe8, 0x45, 0xcf, 0xda, 0x11, 0x9b, 0x1b, 0xb7, 0xa8, 0x36, 0xb9, 0x0f, 0x1a,
	0x13, 0x0e, 0xdb, 0xf1, 0x1a, 0xb6, 0xd9, 0xa4, 0x99, 0x87, 0xd4, 0xf3, 0x2f, 0x00, 0x00, 0xff,
	0xff, 0xa6, 0x6b, 0x5d, 0x05, 0xc5, 0x00, 0x00, 0x00,
}
