// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv/yuntongxun/proto/yuntongxun.proto

package yuntongxun

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendVerificationCodeRequest struct {
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendVerificationCodeRequest) Reset()         { *m = SendVerificationCodeRequest{} }
func (m *SendVerificationCodeRequest) String() string { return proto.CompactTextString(m) }
func (*SendVerificationCodeRequest) ProtoMessage()    {}
func (*SendVerificationCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_48ddc793b54510d9, []int{0}
}

func (m *SendVerificationCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendVerificationCodeRequest.Unmarshal(m, b)
}
func (m *SendVerificationCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendVerificationCodeRequest.Marshal(b, m, deterministic)
}
func (m *SendVerificationCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendVerificationCodeRequest.Merge(m, src)
}
func (m *SendVerificationCodeRequest) XXX_Size() int {
	return xxx_messageInfo_SendVerificationCodeRequest.Size(m)
}
func (m *SendVerificationCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendVerificationCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendVerificationCodeRequest proto.InternalMessageInfo

func (m *SendVerificationCodeRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *SendVerificationCodeRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type SendOrderConfirmationRequest struct {
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OrderId              string   `protobuf:"bytes,3,opt,name=orderId,proto3" json:"orderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendOrderConfirmationRequest) Reset()         { *m = SendOrderConfirmationRequest{} }
func (m *SendOrderConfirmationRequest) String() string { return proto.CompactTextString(m) }
func (*SendOrderConfirmationRequest) ProtoMessage()    {}
func (*SendOrderConfirmationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_48ddc793b54510d9, []int{1}
}

func (m *SendOrderConfirmationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendOrderConfirmationRequest.Unmarshal(m, b)
}
func (m *SendOrderConfirmationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendOrderConfirmationRequest.Marshal(b, m, deterministic)
}
func (m *SendOrderConfirmationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendOrderConfirmationRequest.Merge(m, src)
}
func (m *SendOrderConfirmationRequest) XXX_Size() int {
	return xxx_messageInfo_SendOrderConfirmationRequest.Size(m)
}
func (m *SendOrderConfirmationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendOrderConfirmationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendOrderConfirmationRequest proto.InternalMessageInfo

func (m *SendOrderConfirmationRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *SendOrderConfirmationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SendOrderConfirmationRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type SendShippingNoticeRequest struct {
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	CourierCompany       string   `protobuf:"bytes,2,opt,name=courierCompany,proto3" json:"courierCompany,omitempty"`
	WaybillNumber        string   `protobuf:"bytes,3,opt,name=waybillNumber,proto3" json:"waybillNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendShippingNoticeRequest) Reset()         { *m = SendShippingNoticeRequest{} }
func (m *SendShippingNoticeRequest) String() string { return proto.CompactTextString(m) }
func (*SendShippingNoticeRequest) ProtoMessage()    {}
func (*SendShippingNoticeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_48ddc793b54510d9, []int{2}
}

func (m *SendShippingNoticeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendShippingNoticeRequest.Unmarshal(m, b)
}
func (m *SendShippingNoticeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendShippingNoticeRequest.Marshal(b, m, deterministic)
}
func (m *SendShippingNoticeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendShippingNoticeRequest.Merge(m, src)
}
func (m *SendShippingNoticeRequest) XXX_Size() int {
	return xxx_messageInfo_SendShippingNoticeRequest.Size(m)
}
func (m *SendShippingNoticeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendShippingNoticeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendShippingNoticeRequest proto.InternalMessageInfo

func (m *SendShippingNoticeRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *SendShippingNoticeRequest) GetCourierCompany() string {
	if m != nil {
		return m.CourierCompany
	}
	return ""
}

func (m *SendShippingNoticeRequest) GetWaybillNumber() string {
	if m != nil {
		return m.WaybillNumber
	}
	return ""
}

func init() {
	proto.RegisterType((*SendVerificationCodeRequest)(nil), "yuntongxun.SendVerificationCodeRequest")
	proto.RegisterType((*SendOrderConfirmationRequest)(nil), "yuntongxun.SendOrderConfirmationRequest")
	proto.RegisterType((*SendShippingNoticeRequest)(nil), "yuntongxun.SendShippingNoticeRequest")
}

func init() {
	proto.RegisterFile("srv/yuntongxun/proto/yuntongxun.proto", fileDescriptor_48ddc793b54510d9)
}

var fileDescriptor_48ddc793b54510d9 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xcd, 0x4e, 0xf2, 0x40,
	0x14, 0x86, 0x3f, 0xf8, 0x8c, 0xc6, 0x63, 0x74, 0x71, 0xa2, 0xa6, 0x82, 0x0b, 0xd2, 0x88, 0xb2,
	0x2a, 0x89, 0x5e, 0x02, 0x71, 0xe1, 0x06, 0x13, 0x88, 0x26, 0xc4, 0x55, 0x7f, 0x86, 0x32, 0x09,
	0x9d, 0x33, 0x0e, 0x33, 0x6a, 0xaf, 0xc1, 0x4b, 0xf0, 0x66, 0xcd, 0x4c, 0x01, 0x6b, 0x2d, 0x24,
	0xec, 0xa6, 0x4f, 0x27, 0xcf, 0x39, 0xf3, 0xbe, 0xd0, 0x5d, 0xa8, 0xb7, 0x7e, 0x6e, 0x84, 0x26,
	0x91, 0x7e, 0x18, 0xd1, 0x97, 0x8a, 0x34, 0x95, 0x40, 0xe0, 0x00, 0xc2, 0x0f, 0x69, 0xb5, 0x53,
	0xa2, 0x74, 0xce, 0x8a, 0xab, 0x91, 0x99, 0xf6, 0x59, 0x26, 0x75, 0x5e, 0x5c, 0xf4, 0xc7, 0xd0,
	0x1e, 0x33, 0x91, 0x3c, 0x33, 0xc5, 0xa7, 0x3c, 0x0e, 0x35, 0x27, 0x31, 0xa0, 0x84, 0x8d, 0xd8,
	0xab, 0x61, 0x0b, 0x8d, 0x1d, 0x38, 0x92, 0x33, 0x12, 0x6c, 0x68, 0xb2, 0x88, 0x29, 0xaf, 0xd1,
	0x69, 0xf4, 0x0e, 0x47, 0x65, 0x84, 0x08, 0x7b, 0x31, 0x25, 0xcc, 0x6b, 0xba, 0x5f, 0xee, 0xec,
	0x0b, 0xb8, 0xb4, 0xd2, 0x47, 0x95, 0x30, 0x35, 0x20, 0x31, 0xe5, 0x2a, 0x73, 0xe6, 0x9d, 0xac,
	0x22, 0xcc, 0xd6, 0x56, 0x7b, 0x46, 0x0f, 0x0e, 0xc8, 0x1a, 0x1f, 0x12, 0xef, 0xbf, 0xc3, 0xab,
	0x4f, 0xff, 0xb3, 0x01, 0x17, 0x76, 0xe0, 0x78, 0xc6, 0xa5, 0xe4, 0x22, 0x1d, 0x92, 0xe6, 0xf1,
	0x0e, 0x6f, 0xb8, 0x86, 0x93, 0x98, 0x8c, 0xe2, 0x76, 0xdb, 0x4c, 0x86, 0x22, 0x5f, 0xce, 0xad,
	0x50, 0xbc, 0x82, 0xe3, 0xf7, 0x30, 0x8f, 0xf8, 0x7c, 0xbe, 0x74, 0x15, 0x7b, 0xfc, 0x86, 0xb7,
	0x5f, 0x4d, 0x80, 0xc9, 0x3a, 0x7e, 0x9c, 0xc0, 0x69, 0x5d, 0xc2, 0x78, 0x13, 0x94, 0x5a, 0xdb,
	0xd2, 0x41, 0xeb, 0x3c, 0x28, 0x0a, 0x0c, 0x56, 0x05, 0x06, 0xf7, 0xb6, 0x40, 0xff, 0x1f, 0xbe,
	0xc0, 0x59, 0x6d, 0xce, 0xd8, 0xab, 0xba, 0x37, 0x55, 0xb1, 0x45, 0xfe, 0x04, 0xf8, 0x37, 0x53,
	0xec, 0x56, 0xcd, 0xb5, 0x99, 0x6f, 0xd6, 0x46, 0xfb, 0x8e, 0xdc, 0x7d, 0x07, 0x00, 0x00, 0xff,
	0xff, 0x3c, 0x2f, 0xbe, 0x65, 0xc9, 0x02, 0x00, 0x00,
}
